### ISSUE TITLE
Badge commands should `return` when user is not found (do not attempt to formulate a response)

### ISSUE THREAD

**Issue by Cookie23** [hubot-scripts/hubot-ingress#36]
When using any of the badge commands on a string which isn't a slack user I see an exception in the log. I'd expect for the script to either succeed and allow storage with arbitrary strings or error with a invalid user error.

**Comment by therealklanni** [comment]
Please provide details of what you are doing as well as any relevant log data.

**Comment by Cookie23** [comment]
When doing any badge operation if the @user isn't a known slack user the resulting who object is NULL and creates an unhandled exception when who.id property is accessed. I'm not sure if the implementation should allow storage for arbitrary agent names or only slack users names.

Reproduce with:
>hubot unknownUser has badge verified

Logs yield:
2015-05-26T17:10:44.283629+00:00 app[web.1]: [Tue May 26 2015 17:10:44 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'id' of null
2015-05-26T17:10:44.283637+00:00 app[web.1]:   at Object.badges.del (/app/scripts/badges.coffee:104:7, <js>:72:51)
2015-05-26T17:10:44.283639+00:00 app[web.1]:   at Object.badges.add (/app/scripts/badges.coffee:100:9, <js>:64:18)
2015-05-26T17:10:44.283640+00:00 app[web.1]:   at TextListener.callback (/app/scripts/badges.coffee:153:9, <js>:127:18)
2015-05-26T17:10:44.283642+00:00 app[web.1]:   at TextListener.Listener.call (/app/node_modules/hubot/src/listener.coffee:27:7, <js>:23:14)
2015-05-26T17:10:44.283643+00:00 app[web.1]:   at Robot.receive (/app/node_modules/hubot/src/robot.coffee:197:9, <js>:143:33)
2015-05-26T17:10:44.283645+00:00 app[web.1]:   at SlackBot.Adapter.receive (/app/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
2015-05-26T17:10:44.283646+00:00 app[web.1]:   at SlackBot.message (/app/node_modules/hubot-slack/src/slack.coffee:154:20, <js>:189:21)
2015-05-26T17:10:44.283647+00:00 app[web.1]:   at Client.<anonymous> (/app/node_modules/hubot-slack/src/slack.coffee:1:1, <js>:3:61)
2015-05-26T17:10:44.283649+00:00 app[web.1]:   at Client.emit (events.js:95:17)
2015-05-26T17:10:44.283651+00:00 app[web.1]:   at Client.onMessage (/app/node_modules/hubot-slack/node_modules/slack-client/src/client.js:477:14)
2015-05-26T17:10:44.283653+00:00 app[web.1]:   at WebSocket.<anonymous> (/app/node_modules/hubot-slack/node_modules/slack-client/src/client.js:140:24)
2015-05-26T17:10:44.283654+00:00 app[web.1]:   at WebSocket.emit (events.js:98:17)
2015-05-26T17:10:44.283656+00:00 app[web.1]:   at Receiver.self._receiver.ontext (/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:697:10)
2015-05-26T17:10:44.283657+00:00 app[web.1]:   at Receiver.opcodes.1.finish (/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:397:14)
2015-05-26T17:10:44.283660+00:00 app[web.1]:   at Receiver.add (/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:93:24)
2015-05-26T17:10:44.283659+00:00 app[web.1]:   at Receiver.expectHandler (/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:384:31)
2015-05-26T17:10:44.283662+00:00 app[web.1]:   at CleartextStream.firstHandler (/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:678:22)
2015-05-26T17:10:44.283663+00:00 app[web.1]:   at CleartextStream.emit (events.js:95:17)
2015-05-26T17:10:44.283665+00:00 app[web.1]:   at CleartextStream.<anonymous> (_stream_readable.js:765:14)
2015-05-26T17:10:44.283667+00:00 app[web.1]:   at CleartextStream.emit (events.js:92:17)
2015-05-26T17:10:44.283668+00:00 app[web.1]:   at emitReadable_ (_stream_readable.js:427:10)
2015-05-26T17:10:44.283669+00:00 app[web.1]:   at _stream_readable.js:420:7
2015-05-26T17:10:44.283671+00:00 app[web.1]:   at process._tickCallback (node.js:448:13)
2015-05-26T17:10:44.283672+00:00 app[web.1]:

**Comment by drstevens** [comment]
If you're going to start handling all the possible NPE in hubot and libraries, you've got your work cut out for you.

**Comment by therealklanni** [comment]
After [these lines](https://github.com/hubot-scripts/hubot-ingress/blob/master/src/badges.coffee#L118-L121) we should check the value of `who` and `return` from the function if no user was found. We should also log a warning, about the user not being found.

**Comment by therealklanni** [comment]
Please reopen this issue/pull-request over at [therealklanni/hubot-ingress](https://github.com/therealklanni/hubot-ingress).
