### ISSUE TITLE
Add badge causes TypeError

### ISSUE THREAD

**Issue by wcline** [hubot-scripts/hubot-ingress#71]
Adding badges causes failures

To reproduce:
`hubot I have the founder badge`

Result:

```
[Mon Aug 29 2016 22:34:55 GMT-0400 (EDT)] ERROR TypeError: Cannot read property 'U1G3C40F2' of undefined
  at Object.badges.forUser (/home/will/hubot/node_modules/hubot-ingress/src/badges.coffee:162:12, <js>:108:56)
  at Object.badges.del (/home/will/hubot/node_modules/hubot-ingress/src/badges.coffee:157:7, <js>:99:66)
  at Object.badges.add (/home/will/hubot/node_modules/hubot-ingress/src/badges.coffee:153:9, <js>:91:18)
  at TextListener.callback (/home/will/hubot/node_modules/hubot-ingress/src/badges.coffee:206:9, <js>:154:18)
  at executeListener (/home/will/hubot/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
  at allDone (/home/will/hubot/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
  at /home/will/hubot/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/home/will/hubot/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/home/will/hubot/node_modules/async/lib/async.js:268:15)
  at /home/will/hubot/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
  at nextTickCallbackWith0Args (node.js:420:9)
  at process._tickCallback (node.js:349:13)
```

**Comment by sleavitt** [comment]
@wcline is this still an issue for you? The error "Cannot read property 'U1G3C40F2' of undefined" implies to me that you are using the Slack adapter for hubot, as that looks like the value of a user id in Slack to me. I use this with Slack and within the last day or two was able to successfully add all of my badges at once without issue, and I know of other people using the badges support in hubot-ingress within their Slack as well without any issue. Please advise if this is an open issue for you or not, thanks.

**Comment by therealklanni** [comment]
Please reopen this issue/pull-request over at [therealklanni/hubot-ingress](https://github.com/therealklanni/hubot-ingress).
